### ISSUE TITLE
DISCONNECT OPTION FROM USER

### ISSUE THREAD

**Issue by sayyednazeer** [ankitbko/human-handoff-bot#2]
@ankitbko 
Agent can disconnect from user by clicking on disconnect button.

How user can disconnect from agent..??

**Comment by ankitbko** [comment]
Someone asked the same question in the comments of my blog. I'll just paste what I replied there. Let me know if you have any questions.

This is tricky. The only reliable way to receive any information from user is through the chat itself. Unlike the agent, where we have a button, the user can be on any channel. Other channels (like FB, Skype) dont have any additional "buttons" or a way to send a custom event. I can think the only way to do this is to monitor the user's chat, and based on some keyword such as "disconnect" or "bye" (think through carefully, as these can be false positive) remove the user-agent mapping. Removing the mapping should be same as it is done now.
