### ISSUE TITLE
Missing connection from agent to user

### ISSUE THREAD

**Issue by Xander-Q** [ankitbko/human-handoff-bot#3]
@ankitbko Hey, thank you so much for this application to demonstrate this use case. I could successfully adapt the code to my own application, but ran into a problem according the connection between the agent and the user.

I am able to forward messages from the user to the agent. But when trying to forward messages from the agent to the user the according information in the bot data can't be found. In fact it seems the bot data for the agent address is overridden from setting up the connection to the user and the first message being sent to the user.

I also checked this out on your demo application and it occurs as well. Maybe you have the chance to take a look at it and you're able to fix it or maybe have an idea where this issue comes from.

Thank you in advance.

**Comment by ankitbko** [comment]
This is very weird. The demo application was working both ways last I checked. Did you update any nuget package (specially bot builder)?
Can you check if the user-agent mapping is correctly stored or not. The `User` conversation reference should be stored in the `Agent`'s store.

**Comment by Xander-Q** [comment]
Yes, I updated the packages indeed. I just checked the demo application only updating some of the packages to get it to run, without the bot builder package and the same issue applies.

I attached an image to show you the existing data from step to step.
The agent reference (part 1) is set correctly for the current user and can be obtained later to forward the message of the user to the agent.
The user reference (part 2) is set correctly for the agent as well, despite there are missing two information.
When forwarding a message from the agent to the user (part 3) the user reference disappeared, but the before missing information is obtained. That's why I mentioned it may be overridden during the process.

![missing data in agent user store](https://user-images.githubusercontent.com/29979852/28019966-00b4086c-6583-11e7-82ac-3c62afb8aab3.png)

**Comment by ankitbko** [comment]
Are you using emulator as channel for the "user"?

**Comment by Xander-Q** [comment]
Yes, for testing I use the emulator. But I also have a web application with a webchat control for the user. In this scenario the issue occurs as well.

I just saw the latest issue by @valnav. I'll check back my webchat control scenario and give you an update as soon as possible.

**Comment by ankitbko** [comment]
Could you also try and check if it works in Skype?

**Comment by Xander-Q** [comment]
Well, seemingly I was missing something else when I tried the webchat version some days ago. Anyways it works now and it's good to know, the emulator works in a different way, when handling state information. Thank you for your time.

I will take a look, whether I have the opportunity to check with Skype and give you an update.

**Comment by ankitbko** [comment]
Great it worked. No need to check for Skype now. I'll close this issue. Let me know if you have any other question.
