### ISSUE TITLE
botData.PrivateConversationData.ContainsKey(Constants.USER_KEY) returning false even though mapping has been established

### ISSUE THREAD

**Issue by valnav** [ankitbko/human-handoff-bot#4]
No code change.... except luis endpoint
the user get the message saying the "you are now connected to <agent>" 
The user types a message, which is received by the agent.

but, when the agent types a message it doesnt reach the user. The user is on the emulator. Agent is on the portal. What am I doing wrong?

**Comment by ankitbko** [comment]
Ah.. Emulator won't work for this example. The emulator has its own state storage mechanism which is different from Bot State Service which we use in this example. Use any other channel and it should work.

**Comment by valnav** [comment]
can i do something similar to the agent dashboard where i have the patient also using a webchat hosted page. if so do you have an example of the user in a webchat component.

**Comment by valnav** [comment]
thanks
