### ISSUE TITLE
enabling single agent to have multiple client chats

### ISSUE THREAD

**Issue by valnav** [ankitbko/human-handoff-bot#5]
is there a way, we can support a single agent responding to multiple client chats? i am able to do this for 1:1 client to agent. i can see that i can change the code to make the agent available even if he/she is already on a chat. But, how do i support this in the Agent UI, where i have multiple agent chat windows then.

**Comment by ankitbko** [comment]
You can create multiple web chat instances in a single page which the agent can use to connect with multiple users. For example, instead of having one web chat in the page, have 2 of them loaded side by side, then agent can chat with 2 users.

**Comment by valnav** [comment]
thanks
