### ISSUE TITLE
Connect button giving id=retry

### ISSUE THREAD

**Issue by Mrinnaal** [ankitbko/human-handoff-bot#8]
Thank you so much for the work! It is really worth a shot. But when i try to make the agent available by clicking on connect, the id is returning retry! Could you throw some light over it?

**Comment by ankitbko** [comment]
Can you try to debug and see what errors are occurring?

**Comment by Mrinnaal** [comment]
bro it is resolved!!! actually the problem was with message sending to bot! i forgot to put api/messages in endpoint URL! Cheers! Great work man! Thank you!
